name: instagraph
version: '0.5'
summary: Unofficial Instagraph Client
description: Unofficial Instagraph Client

grade: stable
confinement: strict

apps:
  instagraph:
    command: desktop-launch $SNAP/bin/instagraph
    environment:
      DISABLE_WAYLAND: 1
      IS_DESKTOP: 1
    plugs:
      - unity7
      - x11
      - opengl
      - gsettings
      - network
      - network-bind
      - camera
      - pulseaudio
      - alsa
      - location-control
      - location-observe
      - ubuntu-download-manager

parts:
  launcher:
    plugin: dump
    source: .
    organize:
        launcher.sh: bin/instagraph
  instagraph:
    plugin: qmake
    source: https://github.com/turanmahmudov/Instagraph.git
    qt-version: qt5
    build-packages:
    - ubuntu-sdk-libs
    - qtubuntu-desktop
    - qtdeclarative5-dev
    stage-packages:
    - ubuntu-sdk-libs
    - qtubuntu-desktop
    - qmlscene
    - qml-module-ubuntu-components
    - qtdeclarative5-dev
    - gstreamer1.0-pulseaudio
    - gstreamer1.0-libav
    - gstreamer1.0-plugins-bad
    - gstreamer1.0-plugins-ugly
    - qml-module-qtquick-dialogs
    - qml-module-qtquick-controls
    after: [desktop-qt5]
    organize:
      icon.png: meta/gui/instagraph.png
