name: instagraph
version: '0.1.6'
summary: Unofficial Instagraph Client
description: Unofficial Instagraph Client

grade: stable
confinement: strict

apps:
  instagraph:
    command: desktop-launch $SNAP/bin/instagraph
    plugs:
      - unity7
      - x11
      - opengl
      - gsettings
      - network
      - network-bind
      - camera

parts:
  launcher:
    plugin: dump
    source: .
    organize:
        launcher.sh: bin/instagraph
  instagraph:
    plugin: qmake
    source: https://github.com/turanmahmudov/Instagraph.git
    qt-version: qt5
    build-packages:
    - ubuntu-sdk-libs
    - qtubuntu-desktop
    - qmlscene
    - qml-module-ubuntu-components
    - qtdeclarative5-dev
    stage-packages:
    - ubuntu-sdk-libs
    - qtubuntu-desktop
    - qmlscene
    - qml-module-ubuntu-components
    - qtdeclarative5-dev
    after: [desktop-qt5]
    organize:
      icon.png: setup/gui/instagraph.png
